spring.application.name=achievement-tracker-backend
server.port=${PORT:8080}

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Database Configuration (Render PostgreSQL)
spring.datasource.url=jdbc:postgresql://dpg-d7o6tq77f7vs73878gbg-a.singapore-postgres.render.com:5432/backend_databases?sslmode=require&sslfactory=org.postgresql.ssl.NonValidatingFactory
spring.datasource.username=backend_databases_user
spring.datasource.password=k51UMNz6M76iuTDQQU58ruXhHNeRoI2W
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

